/**
 * SteamScope — Chinese Label Mappings
 * Maps English Steam tags / genres / categories to Chinese names.
 * Display format: "中文名 (English)" or just "English" if unmapped.
 */

const ZH_GENRE = {
  "360 Video":               "360° 全景视频",
  "Accounting":              "会计软件",
  "Action":                  "动作",
  "Adventure":               "冒险",
  "Animation & Modeling":    "动画与建模",
  "Audio Production":        "音频制作",
  "Casual":                  "休闲",
  "Design & Illustration":   "设计与插画",
  "Documentary":             "纪录短片",
  "Early Access":            "抢先体验",
  "Education":               "教育",
  "Episodic":                "分集剧情",
  "Free To Play":            "免费游玩",
  "Game Development":        "游戏开发",
  "Gore":                    "血腥",
  "Indie":                   "独立游戏",
  "Massively Multiplayer":   "大型多人在线",
  "Movie":                   "互动电影",
  "Nudity":                  "裸露",
  "Photo Editing":           "照片编辑",
  "RPG":                     "角色扮演",
  "Racing":                  "竞速",
  "Sexual Content":          "色情内容",
  "Short":                   "小游戏",
  "Simulation":              "模拟",
  "Software Training":       "软件教程",
  "Sports":                  "体育",
  "Strategy":                "策略",
  "Tutorial":                "指南",
  "Utilities":               "实用工具",
  "Video Production":        "视频制作",
  "Violent":                 "暴力",
  "Web Publishing":          "网页发布",
};

const ZH_CATEGORY = {
  "Captions available":            "字幕支持",
  "Co-op":                         "合作模式",
  "Commentary available":          "解说可用",
  "Cross-Platform Multiplayer":    "跨平台联机",
  "Family Sharing":                "家庭共享",
  "Full controller support":       "完全控制器支持",
  "HDR available":                 "HDR 支持",
  "In-App Purchases":              "应用内购",
  "Includes Source SDK":           "含 Source SDK",
  "Includes level editor":         "含关卡编辑器",
  "LAN Co-op":                     "局域网合作",
  "LAN PvP":                       "局域网对战",
  "MMO":                           "大型多人在线",
  "Multi-player":                  "多人游戏",
  "Online Co-op":                  "在线合作",
  "Online PvP":                    "在线对战",
  "Partial Controller Support":    "部分控制器支持",
  "PvP":                           "玩家对战",
  "Remote Play Together":          "远程同乐",
  "Remote Play on Phone":          "手机远程畅玩",
  "Remote Play on TV":             "电视远程畅玩",
  "Remote Play on Tablet":         "平板远程畅玩",
  "Shared/Split Screen":           "分屏游戏",
  "Shared/Split Screen Co-op":     "分屏合作",
  "Shared/Split Screen PvP":       "分屏对战",
  "Single-player":                 "单人游戏",
  "Stats":                         "统计数据",
  "Steam Achievements":            "Steam 成就",
  "Steam Cloud":                   "Steam 云存档",
  "Steam Leaderboards":            "Steam 排行榜",
  "Steam Timeline":                "Steam 时间线",
  "Steam Trading Cards":           "Steam 集换式卡牌",
  "Steam Turn Notifications":      "Steam 回合通知",
  "Steam Workshop":                "Steam 创意工坊",
  "SteamVR Collectibles":          "SteamVR 收藏品",
  "Tracked Controller Support":    "追踪手柄支持",
  "VR Only":                       "仅 VR",
  "VR Support":                    "VR 支持",
  "VR Supported":                  "VR 支持",
  "Valve Anti-Cheat enabled":      "VAC 反作弊",
};

const ZH_TAG = {
  "2D":                       "2D 画面",
  "2D Fighter":               "2D 格斗",
  "2D Platformer":            "2D 平台跳跃",
  "3D":                       "3D 画面",
  "3D Fighter":               "3D 格斗",
  "3D Platformer":            "3D 平台跳跃",
  "3D Vision":                "3D 视觉",
  "4 Player Local":           "4 人本地",
  "4X":                       "4X 策略",
  "Abstract":                 "抽象",
  "Action":                   "动作",
  "Action RPG":               "动作角色扮演",
  "Action Roguelike":         "动作 Roguelike",
  "Action-Adventure":         "动作冒险",
  "Addictive":                "上瘾",
  "Adventure":                "冒险",
  "Agriculture":              "农业",
  "Aliens":                   "外星人",
  "America":                  "美国",
  "Anime":                    "动漫",
  "Arcade":                   "街机",
  "Arena Shooter":            "竞技场射击",
  "Artificial Intelligence":  "人工智能",
  "Assassin":                 "刺客",
  "Atmospheric":              "氛围感",
  "Automobile Sim":           "汽车模拟",
  "Base-Building":            "基地建造",
  "Baseball":                 "棒球",
  "Basketball":               "篮球",
  "Battle Royale":            "大逃杀",
  "Beat 'em up":              "清版动作",
  "Beautiful":                "画面精美",
  "Benchmark":                "性能测试",
  "Bikes":                    "自行车",
  "Blood":                    "血腥",
  "Board Game":               "桌游",
  "Bowling":                  "保龄球",
  "Building":                 "建造",
  "Bullet Hell":              "弹幕地狱",
  "Bullet Time":              "子弹时间",
  "CRPG":                     "经典角色扮演",
  "Card Battler":             "卡牌战斗",
  "Card Game":                "卡牌游戏",
  "Cartoon":                  "卡通",
  "Cartoony":                 "卡通风格",
  "Casual":                   "休闲",
  "Character Action Game":    "角色动作",
  "Character Customization":  "角色自定义",
  "Chess":                    "国际象棋",
  "Choices Matter":           "选择导向",
  "Choose Your Own Adventure":"互动叙事",
  "Cinematic":                "电影化",
  "City Builder":             "城市建设",
  "Class-Based":              "职业系统",
  "Classic":                  "经典",
  "Clicker":                  "点击类",
  "Co-op":                    "合作",
  "Co-op Campaign":           "合作战役",
  "Cold War":                 "冷战",
  "Collectathon":             "收集类",
  "Colorful":                 "色彩丰富",
  "Combat":                   "战斗",
  "Combat Racing":            "战斗竞速",
  "Comedy":                   "喜剧",
  "Comic Book":               "漫画",
  "Competitive":              "竞技",
  "Conspiracy":               "阴谋论",
  "Controller":               "手柄支持",
  "Conversation":             "对话",
  "Cooking":                  "烹饪",
  "Crafting":                 "合成与制作",
  "Creature Collector":       "生物收集",
  "Crime":                    "犯罪",
  "Crowdfunded":              "众筹",
  "Cult Classic":             "邪典经典",
  "Cute":                     "可爱",
  "Cyberpunk":                "赛博朋克",
  "Cycling":                  "骑行",
  "Dark":                     "黑暗",
  "Dark Comedy":              "黑色幽默",
  "Dark Fantasy":             "暗黑奇幻",
  "Dark Humor":               "黑色幽默",
  "Dating Sim":               "恋爱模拟",
  "Deckbuilding":             "牌组构筑",
  "Demons":                   "恶魔",
  "Design & Illustration":    "设计与插画",
  "Destruction":              "可破坏环境",
  "Detective":                "侦探",
  "Difficult":                "高难度",
  "Dinosaurs":                "恐龙",
  "Diplomacy":                "外交",
  "Dog":                      "狗",
  "Dragons":                  "龙",
  "Drama":                    "剧情",
  "Driving":                  "驾驶",
  "Dungeon Crawler":          "地牢探险",
  "Dungeons & Dragons":       "龙与地下城",
  "Dynamic Narration":        "动态叙述",
  "e-sports":                 "电子竞技",
  "Early Access":             "抢先体验",
  "Economy":                  "经济系统",
  "Education":                "教育",
  "Emotional":                "情感",
  "Episodic":                 "分集",
  "Experimental":             "实验性",
  "Exploration":              "探索",
  "FPS":                      "第一人称射击",
  "FMV":                      "全动态影像",
  "Faith":                    "信仰",
  "Family Friendly":          "阖家欢乐",
  "Fantasy":                  "奇幻",
  "Fast-Paced":               "快节奏",
  "Female Protagonist":       "女主角",
  "Fighting":                 "格斗",
  "First-Person":             "第一人称",
  "Fishing":                  "钓鱼",
  "Flight":                   "飞行",
  "Football (Soccer)":        "足球",
  "Foreign":                  "异国",
  "Free to Play":             "免费游玩",
  "Funny":                    "搞笑",
  "Futuristic":               "未来风格",
  "Gambling":                 "赌博",
  "Game Development":         "游戏开发",
  "GameMaker":                "GameMaker 引擎",
  "God Game":                 "上帝模拟",
  "Golf":                     "高尔夫",
  "Gore":                     "血腥",
  "Gothic":                   "哥特",
  "Grand Strategy":           "大战略",
  "Great Soundtrack":         "优质原声",
  "Grid-Based Movement":      "网格移动",
  "Gun Customization":        "枪械定制",
  "Hack and Slash":           "砍杀",
  "Hand-drawn":               "手绘风格",
  "Hardware":                 "硬件",
  "Heist":                    "抢劫",
  "Hex Grid":                 "六角格",
  "Hidden Object":            "寻物解谜",
  "Historical":               "历史",
  "Horror":                   "恐怖",
  "Horses":                   "马",
  "Hunting":                  "狩猎",
  "Idler":                    "放置类",
  "Illuminati":               "光明会",
  "Immersive Sim":            "沉浸式模拟",
  "Indie":                    "独立游戏",
  "Intentionally Awkward Controls":"刻意蹩脚操控",
  "Interactive Fiction":      "互动小说",
  "Inventory Management":     "物品管理",
  "Investigation":            "调查",
  "Isometric":                "等距视角",
  "JRPG":                     "日式角色扮演",
  "Jet":                      "喷气式飞机",
  "Kickstarter":              "众筹游戏",
  "LGBTQ+":                   "LGBTQ+",
  "LEGO":                     "乐高",
  "Lara Croft":               "劳拉·克劳馥",
  "Lemmings":                 "旅鼠",
  "Level Editor":             "关卡编辑器",
  "Linear":                   "线性剧情",
  "Local Co-Op":              "本地合作",
  "Local Multiplayer":        "本地多人",
  "Logic":                    "逻辑解谜",
  "Lore-Rich":                "世界观丰富",
  "Lovecraftian":             "洛夫克拉夫特式",
  "MMORPG":                   "大型多人在线角色扮演",
  "MOBA":                     "多人在线战术竞技",
  "Magic":                    "魔法",
  "Management":               "经营管理",
  "Mars":                     "火星",
  "Martial Arts":             "武术",
  "Massively Multiplayer":    "大型多人在线",
  "Masterpiece":              "神作",
  "Match 3":                  "三消",
  "Mature":                   "成人",
  "Mechs":                    "机甲",
  "Medieval":                 "中世纪",
  "Memes":                    "梗文化",
  "Metroidvania":             "银河恶魔城",
  "Military":                 "军事",
  "Mini Golf":                "迷你高尔夫",
  "Minigames":                "小游戏合集",
  "Minimalist":               "极简风格",
  "Mining":                   "采矿",
  "Moddable":                 "支持 MOD",
  "Modern":                   "现代",
  "Motorbike":                "摩托车",
  "Motorsports":              "赛车运动",
  "Mouse only":               "仅鼠标",
  "Movie":                    "电影",
  "Multiplayer":              "多人",
  "Multiple Endings":         "多结局",
  "Music":                    "音乐",
  "Music-Based Procedural Generation":"音乐驱动生成",
  "Mystery":                  "悬疑",
  "Mythology":                "神话",
  "Narration":                "旁白",
  "Nature":                   "自然",
  "Naval":                    "海战",
  "Naval Combat":             "海战",
  "Ninja":                    "忍者",
  "Noir":                     "黑色电影",
  "Nonlinear":                "非线性",
  "Nostalgia":                "怀旧",
  "Nudity":                   "裸露",
  "Offroad":                  "越野",
  "Old School":               "复古风格",
  "On-Rails Shooter":         "轨道射击",
  "Open World":               "开放世界",
  "Open World Survival Craft":"开放世界生存建造",
  "Otome":                    "乙女",
  "Parkour":                  "跑酷",
  "Parody":                   "恶搞",
  "Party Game":               "派对游戏",
  "Party-Based RPG":          "小队角色扮演",
  "Perma Death":              "永久死亡",
  "Philosophical":            "哲学",
  "Photo Editing":            "照片编辑",
  "Physics":                  "物理模拟",
  "Pinball":                  "弹球",
  "Pirates":                  "海盗",
  "Pixel Graphics":           "像素风格",
  "Platformer":               "平台跳跃",
  "Point & Click":            "点击解谜",
  "Political":                "政治",
  "Politics":                 "政治",
  "Pool":                     "台球",
  "Post-apocalyptic":         "末世",
  "Precision Platformer":     "精准平台",
  "Procedural Generation":    "程序生成",
  "Programming":              "编程",
  "Psychedelic":              "迷幻",
  "Psychological":            "心理",
  "Psychological Horror":     "心理恐怖",
  "Puzzle":                   "解谜",
  "Puzzle-Platformer":        "解谜平台",
  "PvE":                      "玩家 vs 环境",
  "PvP":                      "玩家 vs 玩家",
  "Quick-Time Events":        "快速反应事件",
  "RPG":                      "角色扮演",
  "RPGMaker":                 "RPG Maker",
  "RTS":                      "即时战略",
  "Racing":                   "竞速",
  "Real Time Tactics":        "即时战术",
  "Real-Time":                "实时",
  "Real-Time with Pause":     "即时可暂停",
  "Realistic":                "写实",
  "Relaxing":                 "放松",
  "Remake":                   "重制版",
  "Replay Value":             "反复游玩",
  "Resource Management":      "资源管理",
  "Retro":                    "复古",
  "Rhythm":                   "音游",
  "Robots":                   "机器人",
  "Rogue-like":               "Roguelike",
  "Rogue-lite":               "Roguelite",
  "Roguevania":               "Roguevania",
  "Romance":                  "恋爱",
  "Rome":                     "罗马",
  "Runner":                   "跑酷",
  "Sandbox":                  "沙盒",
  "Satire":                   "讽刺",
  "Sci-fi":                   "科幻",
  "Science":                  "科学",
  "Score Attack":             "刷分",
  "Sexual Content":           "色情内容",
  "Shoot 'Em Up":             "弹幕射击",
  "Shooter":                  "射击",
  "Short":                    "短篇",
  "Side Scroller":            "横版卷轴",
  "Simulation":               "模拟",
  "Singleplayer":             "单人",
  "Skeeball":                 "滑雪球",
  "Skateboarding":            "滑板",
  "Skating":                  "滑冰",
  "Skiing":                   "滑雪",
  "Sniper":                   "狙击",
  "Snow":                     "雪地",
  "Snowboarding":             "单板滑雪",
  "Social Deduction":         "社交推理",
  "Software":                 "软件",
  "Sokoban":                  "推箱子",
  "Souls-like":               "魂类",
  "Soundtrack":               "原声音乐",
  "Space":                    "太空",
  "Space Sim":                "太空模拟",
  "Spectacle fighter":        "华丽格斗",
  "Spelling":                 "拼写",
  "Split Screen":             "分屏",
  "Sports":                   "体育",
  "Star Wars":                "星球大战",
  "Stealth":                  "潜行",
  "Steampunk":                "蒸汽朋克",
  "Story Rich":               "剧情丰富",
  "Strategy":                 "策略",
  "Strategy RPG":             "策略角色扮演",
  "Stylized":                 "风格化",
  "Submarine":                "潜艇",
  "Superhero":                "超级英雄",
  "Supernatural":             "超自然",
  "Surreal":                  "超现实",
  "Survival":                 "生存",
  "Survival Horror":          "生存恐怖",
  "Swordplay":                "剑术",
  "Tabletop":                 "桌面游戏",
  "Tactical":                 "战术",
  "Tactical RPG":             "战术角色扮演",
  "Tanks":                    "坦克",
  "Team-Based":               "团队",
  "Tennis":                   "网球",
  "Text-Based":               "文字游戏",
  "Third Person":             "第三人称",
  "Third-Person Shooter":     "第三人称射击",
  "Thriller":                 "惊悚",
  "Time Attack":              "计时赛",
  "Time Management":          "时间管理",
  "Time Manipulation":        "时间操控",
  "Time Travel":              "时间旅行",
  "Top-Down":                 "俯视视角",
  "Top-Down Shooter":         "俯视射击",
  "Touch-Friendly":           "触屏友好",
  "Tower Defense":            "塔防",
  "TrackIR":                  "头部追踪",
  "Trading":                  "交易",
  "Trading Card Game":        "集换式卡牌",
  "Trains":                   "火车",
  "Transhumanism":            "超人类主义",
  "Trivia":                   "问答",
  "Turn-Based":               "回合制",
  "Turn-Based Combat":        "回合制战斗",
  "Turn-Based Strategy":      "回合制策略",
  "Turn-Based Tactics":       "回合制战术",
  "Tutorial":                 "教程",
  "Twin Stick Shooter":       "双摇杆射击",
  "Typing":                   "打字",
  "Underground":              "地下",
  "Underwater":               "水下",
  "Unforgiving":              "毫不留情",
  "Utilities":                "工具",
  "VR":                       "VR",
  "Vampire":                  "吸血鬼",
  "Video Production":         "视频制作",
  "Vikings":                  "维京",
  "Villain Protagonist":      "反派主角",
  "Violent":                  "暴力",
  "Visual Novel":             "视觉小说",
  "Voice Control":            "语音控制",
  "Voxel":                    "体素",
  "Walking Simulator":        "步行模拟",
  "War":                      "战争",
  "Wargame":                  "兵棋推演",
  "Warhammer 40K":            "战锤 40K",
  "Well-Written":             "文笔优秀",
  "Werewolves":               "狼人",
  "Western":                  "西部",
  "Word Game":                "文字游戏",
  "World War I":              "第一次世界大战",
  "World War II":             "第二次世界大战",
  "Wrestling":                "摔角",
  "Zombies":                  "僵尸",
  "eBook":                    "电子书",
};

/**
 * Return display label: "中文名 (EnglishName)" or just "EnglishName" if unmapped.
 */
function zhLabel(en, dict) {
  if (!en) return "";
  if (dict && dict[en]) return dict[en] + " (" + en + ")";
  // Try all three dictionaries
  const cn = ZH_GENRE[en] || ZH_CATEGORY[en] || ZH_TAG[en];
  if (cn) return cn + " (" + en + ")";
  return en;
}

/**
 * Convenience: zhTag("Indie") → "独立游戏 (Indie)"
 */
function zhTag(en) { return zhLabel(en, ZH_TAG); }

/**
 * Convenience: zhGenre("Action") → "动作 (Action)"
 */
function zhGenre(en) { return zhLabel(en, ZH_GENRE); }

/**
 * Convenience: zhCategory("Single-player") → "单人游戏 (Single-player)"
 */
function zhCategory(en) { return zhLabel(en, ZH_CATEGORY); }
